version: "3"
services:
  client:
    build: "./client"
    ports:
      - "3000:5173"
    volumes:
      - /src/node_modules
      - ./client:/src
      - dist:/src/dist
    depends_on: 
      - server
    restart: on-failure

  server:
    build: "./server"
    ports:
      - "3001:3000"
    volumes:
      - /src/node_modules
      - ./server:/src
    depends_on:
      - db-postgres
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@db-postgres/sailplane
    restart: on-failure
  
  db-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sailplane

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - dist:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  db:
  dist: